version: '3.7'

services:
  main:
    build:
      context: .
      target: prod
    ports:
      - ${SERVER_PORT:-3000}:3000
      - 9229:9229
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql_data: